version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    image: geoweb/yidp-core-ui
    volumes:
      - '.:/app'
    ports:
     - "8080:8080"
    environment:
      - CLIENT_ID=nbH4LKwhGrN4M8OPloE8yndqHK0x9y5hhjz6HjlT
      - CLIENT_SECRET=emvozCHanvJMX27TTOurZMxjokPGdYKVEI1NgaCRKFYF6XD18JSau8puT0mWdxsDMTD719sZotHhrOt2cmKgJs1lm1kA14Dsr7BeL2FksLTNN4lL50MsQ0i752gzNDfy

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    image: geoweb/yidp-core-ui-nginx
    ports:
    - "80:80"
    depends_on:
      - web

networks:
  default:
    external:
      name: geonode_default
